### ISSUE TITLE
EXE version may be infected- multiple VirusTotal detections-such were not there in CMD file

### ISSUE THREAD

**Issue by naks110** [shu6h4m/MicroSoft_Activator#2]
[Microsoft Activator Executeable.exe](https://github.com/shu6h4m/MicroSoft_Activator/blob/main/Microsoft%20Activator%20Executeable.exe)

https://www.virustotal.com/gui/file/be5678bc7dfa49fd032c2504a9c21f53244f78ae690611608ebf5267db7825a0?nocache=1

CRITICAL 1
HIGH 289
MEDIUM 9
LOW 50
1 match for rule TAIDOOR - Chinese RAT by Ariel Millahuel from SOC Prime Threat Detection Marketplace
This RAT was discovered by CISA. Taidoor is installed on a target’s system as a service dynamic link library (DLL) and is comprised of two files. The first file is a loader, which is started as a service. The loader decrypts the second file, and executes it in memory, which is the main Remote Access Trojan (RAT).
...
1 match for rule Root Certificate Installed by oscd.community, @redcanary, Zach Stanford @svch0st from Sigma Integrated Rule Set (GitHub)
Adversaries may install a root certificate on a compromised system to avoid warnings when connecting to adversary controlled web servers.
... AND multiple

// Whereas your CMD file comes out as clean:
https://www.virustotal.com/gui/file/3673a20dc371c20b324b3909904a2a3731f9f7ab01cc05a3c69fc70532f45c7e

**Comment by shu6h4m** [comment]
# Hi [Nakshatra](https://github.com/naks110), thanks for reaching out and raising this issue.

I am well aware about this issue, Just to save my time I used some **online platform** to convert the **.cmd file to .exe** and from there these malicious scripts got added to the cmd file.
But there is nothing to worry about, windows defender or other antivirus tool don't allow this EXE file to run on your system and to activate windows one has to use CMD method only.

Thankyou !
